import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const links = [
    { label: 'Email', href: 'mailto:jonathanfabien675@gmail.com', display: 'jonathanfabien675@gmail.com' },
    { label: 'LinkedIn', href: 'https://www.linkedin.com/in/jonathan-fabien-3b43bb1b3/', display: 'linkedin.com/in/jonathan-fabien-3b43bb1b3' },
    { label: 'GitHub', href: 'https://github.com/PapiFab1', display: 'github.com/PapiFab1' },
];
export default function Contact() {
    return (_jsx("section", { id: "contact", className: "bg-gray-950 text-white py-28 px-6 border-t border-white/5", children: _jsxs("div", { className: "max-w-3xl mx-auto", children: [_jsxs("div", { className: "flex items-center gap-4 mb-10", children: [_jsx("div", { className: "h-px w-8 bg-blue-500" }), _jsx("p", { className: "text-blue-400 text-xs tracking-[0.5em] uppercase font-medium", children: "Contact" })] }), _jsx("h2", { className: "text-3xl font-black mb-10", children: "Let's connect." }), _jsx("div", { className: "space-y-3 mb-12", children: links.map((link) => (_jsxs("a", { href: link.href, target: link.href.startsWith('mailto') ? undefined : '_blank', rel: "noreferrer", style: { clipPath: 'polygon(0 0, calc(100% - 14px) 0, 100% 100%, 0 100%)' }, className: "group flex items-center justify-between max-w-md px-5 py-4\n                         bg-gray-900 hover:bg-blue-600\n                         border-l-[3px] border-blue-500/40 hover:border-transparent\n                         transition-colors duration-150", children: [_jsx("span", { className: "text-gray-500 group-hover:text-blue-100 text-xs tracking-[0.4em] uppercase transition-colors", children: link.label }), _jsx("span", { className: "text-sm text-gray-300 group-hover:text-white transition-colors", children: link.display })] }, link.label))) }), _jsxs("a", { href: "/resume.pdf", download: true, style: { clipPath: 'polygon(0 0, calc(100% - 14px) 0, 100% 100%, 0 100%)' }, className: "inline-flex items-center gap-4 px-8 py-4\n                     bg-blue-600 hover:bg-blue-500\n                     text-white font-bold text-sm tracking-[0.3em] uppercase\n                     transition-colors duration-150", children: [_jsx("span", { children: "\u2193" }), _jsx("span", { children: "Download Resume" })] })] }) }));
}
